/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRoundsRouteImport } from './routes/saved-rounds'
import { Route as RoundTrackerRouteImport } from './routes/round-tracker'
import { Route as PrintRouteImport } from './routes/print'
import { Route as LagputRouteImport } from './routes/lagput'
import { Route as IndexRouteImport } from './routes/index'

const SavedRoundsRoute = SavedRoundsRouteImport.update({
  id: '/saved-rounds',
  path: '/saved-rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundTrackerRoute = RoundTrackerRouteImport.update({
  id: '/round-tracker',
  path: '/round-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LagputRoute = LagputRouteImport.update({
  id: '/lagput',
  path: '/lagput',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lagput': typeof LagputRoute
  '/print': typeof PrintRoute
  '/round-tracker': typeof RoundTrackerRoute
  '/saved-rounds': typeof SavedRoundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lagput': typeof LagputRoute
  '/print': typeof PrintRoute
  '/round-tracker': typeof RoundTrackerRoute
  '/saved-rounds': typeof SavedRoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lagput': typeof LagputRoute
  '/print': typeof PrintRoute
  '/round-tracker': typeof RoundTrackerRoute
  '/saved-rounds': typeof SavedRoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lagput' | '/print' | '/round-tracker' | '/saved-rounds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lagput' | '/print' | '/round-tracker' | '/saved-rounds'
  id:
    | '__root__'
    | '/'
    | '/lagput'
    | '/print'
    | '/round-tracker'
    | '/saved-rounds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LagputRoute: typeof LagputRoute
  PrintRoute: typeof PrintRoute
  RoundTrackerRoute: typeof RoundTrackerRoute
  SavedRoundsRoute: typeof SavedRoundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved-rounds': {
      id: '/saved-rounds'
      path: '/saved-rounds'
      fullPath: '/saved-rounds'
      preLoaderRoute: typeof SavedRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round-tracker': {
      id: '/round-tracker'
      path: '/round-tracker'
      fullPath: '/round-tracker'
      preLoaderRoute: typeof RoundTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lagput': {
      id: '/lagput'
      path: '/lagput'
      fullPath: '/lagput'
      preLoaderRoute: typeof LagputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LagputRoute: LagputRoute,
  PrintRoute: PrintRoute,
  RoundTrackerRoute: RoundTrackerRoute,
  SavedRoundsRoute: SavedRoundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
